server:
  port: 9002

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: my-beyti
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: false
    schemas: my-beyti
    table: party_flyway_schema_history
